Re add Manufacturer and Supplier Pages
PrestaShop/gsitemap pull request #147
Opened 2021-12-28 14:36 UTC by sanctusmob

Re add Manufacturer and Supplier Pages to Sitemap XML.
For some unknown reason they removed in "Fix all reported bugs #53"

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Re add Manufacturer and Supplier Pages to Sitemap XML
| Type?         | improvement / new feature
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Already tested

2021-12-28 15:21 UTC, PierreRambaud requested changes
Could you please use spaces instead of tabs everywhere?

2021-12-28 15:40 UTC, sanctusmob commented
Done

2021-12-28 15:51 UTC, PierreRambaud commented on gsitemap.php
> +        if (method_exists('ShopUrl', 'resetMainDomainCache'))
Missing encapsulation?

2021-12-28 15:51 UTC, PierreRambaud commented on gsitemap.php
> +            ))
Missing encapsulation :thinking:

2021-12-29 11:42 UTC, sanctusmob commented on gsitemap.php
> +        if (method_exists('ShopUrl', 'resetMainDomainCache'))
Fixed

2021-12-29 11:42 UTC, sanctusmob commented on gsitemap.php
> +            ))
Fixed

2021-12-30 08:37 UTC, PierreRambaud requested changes
Cs fixer and phpstan are still not happy

2021-12-30 11:23 UTC, sanctusmob commented
Can you check the phpstan error?

Line 605    Parameter #1 $id of class Supplier constructor expects null, int given.

From Supplier class
/**
     * SupplierCore constructor.
     *
     * @param int|null $id
     * @param int|null $idLang
     */
    public function __construct($id = null, $idLang = null)

phpstan should not be complain about that...

2021-12-30 16:49 UTC, PierreRambaud commented
> SupplierCore

Not in old Prestashop versions: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.8/classes/Supplier.php#L94

2021-12-31 13:20 UTC, sanctusmob commented
and? how to solve this? Obvious constructor can get integer values.

2022-01-04 14:56 UTC, matks commented
@sanctusmob phpstan can ignore errors using configuration https://phpstan.org/user-guide/ignoring-errors

2022-01-12 15:51 UTC, atomiix commented on gsitemap.php
> +                    'caption' => Tools::substr(htmlspecialchars(strip_tags($manufacturer->short_description)), 0, 350), /** @phpstan-ignore-line */
```suggestion
                    'caption' => Tools::substr(htmlspecialchars(strip_tags($manufacturer->short_description)), 0, 350), /* @phpstan-ignore-line */
```

2022-01-31 11:51 UTC, sanctusmob commented
We are ok?

2022-03-01 10:14 UTC, atomiix approved these changes

2022-03-11 15:09 UTC, AureRita requested changes
HI @sanctusmob ,

Can we have an issue and the steps to reproduce to let the team QA test it correctly ?

Thank you :)

2022-04-19 10:05 UTC, matks commented
Hello,

It looks like this PR is now stale. I close it as our rules state it "Pull Requests may be closed after 30 days of inactivity following a request for modifications." (https://www.prestashop-project.org/maintainers-guide/reviewing-pull-requests/)

Thank you

2022-04-19 10:05 UTC, closed without merging