Remove function "GSITEMAP_CHECK_IMAGE_FILE"
PrestaShop/gsitemap pull request #169
Opened 2023-11-16 19:39 UTC by ShaiMagal

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Function GSITEMAP_CHECK_IMAGE_FILE in this module is crazy thing, and "every second" customer enable it without knowing impact, for example on performance (there is EVERY image "opened" via get_headers). If eshop have for example 100 000 images, every single images is analyzes, so, in most of cases error 500. But maybe worse is problem, they enable this, and in bigger eshops or slow webhosting it doesn't run to end, so sitemap is outdated years (I saw this about 5 times already). We should remove this. It's useful function.
| Type?         | refacto
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #34572 + #32625 + #18508
| How to test?  | Regenerate sitemap

2023-11-16 19:46 UTC, Hlavtox reviewed
You also need to change the version in config.xml, but otherwise it's OK for me. ;-)

2023-11-16 20:50 UTC, ShaiMagal commented
@Hlavtox Ahhh, config.xml edit done :)

2023-11-17 17:03 UTC, matthieu-rolland reviewed
Looks like the csfixer is blocking the PR

To fix this you can run this command from the root of your project and then commit and push the modifications:

`php vendor/bin/php-cs-fixer fix`

2023-11-17 17:26 UTC, Hlavtox requested changes
Code style fix is needed, please avoid autoformatting in the IDE, because it's using a different style apparently. 

Also, it creates extra code changes and making the PR harder to review. 👍

2023-11-23 12:31 UTC, ShaiMagal commented
@Hlavtox I rewrite changes manually from scratch.

@matthieu-rolland I don't have project for it (small changes).
Is there any other option how to fix it manully? I don't know, what to fix to be honest :) I see it's test "PHP tests / PHP-CS-Fixer (pull_request)" - but I don't know, what to change.

2023-11-25 10:56 UTC, Hlavtox requested changes
Bad upgrade file name and method name. ;-)

2023-11-25 11:02 UTC, ShaiMagal commented
@Hlavtox fixed. Tests green now.

2023-11-25 11:04 UTC, Hlavtox commented
Nice, now, we just need to squash those commits so there is only 1. ;-)

2023-11-25 11:47 UTC, Hlavtox approved these changes

2023-11-29 16:28 UTC, Hlavtox commented
Verified the behavior, everything works correctly, including the upgrade. :-)

Minor issues found when testing this - fixed here - https://github.com/PrestaShop/PrestaShop/pull/34731.

2023-11-29 16:28 UTC, merged